version: "3"
services:
  pls_nginx:
    container_name: pls-local-server
    image: nginx:alpine
    ports:
      - "8002:8002"
    depends_on:
      - pls_app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-local-ws
    stdin_open: true
    tty: true
  pls_database:
    container_name: pls-local-db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: pls
      TZ: "Asia/Manila"
      PGTZ: "Asia/Manila"
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - app-local-ws
  pls_app:
    container_name: pls-local-app
    build: .
    environment:
      NODE_ENV: development
      TZ: "Asia/Manila"
    ports:
      - "3333:3333"
    volumes:
      - ./project:/app
      - /app/node_modules
    networks:
      - app-local-ws
    stdin_open: true
    tty: true
    depends_on:
      - pls_database
networks:
  app-local-ws:
    driver: bridge
